service: videonet-api

plugins: 
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-southeast-2

functions:
  graphql:
    handler: ./src/handler.server
    events:
      - http:
          path: /
          method: post
          cors: true
  playground:
    handler: ./src/handler.playground
    events:
      - http:
          path: /
          method: get
          cors: true

package:
  include:
    - src/schema.graphql